// export interface WizardsResponse {
//     count: number;
//     next: string;
//     previous: null;
//     results: Result[];
// }

// export interface Result {
//     name: string;
//     id: string;
// }
// Generated by https://quicktype.io

export interface WizardsResponse {
    id:               string;
    name:             string;
    alternate_names:  string[];
    dateOfBirth:      null | string;
    yearOfBirth:      number | null;
    wizard:           boolean;
    hogwartsStudent:  boolean;
    hogwartsStaff:    boolean;
    actor:            string;
    alternate_actors: string[];
    alive:            boolean;
    image:            string;
}
